### PR TITLE
Prevent including source directory from include directory

### LINKED ISSUE #118: Garbage collection breaks build
Commit [#114ca85](https://github.com/xlnt-community/xlnt/commit/114ca8512ee3a463a3e41749836d145c62621b7d) for "Fix garbage collection of formats" (pull request https://github.com/xlnt-community/xlnt/pull/115) causes my build to fail with

`xxx\include\xlnt\styles\format.hpp(30,10): error C1083: Cannot open include file: 'detail/implementations/format_impl.hpp': No such file or directory (compiling source file 'zzz')
`

Because I'm linking with a pre-built xlnt library, my project only lists "xlnt/include" in its include directories list. However, this commit wants me to add "xlnt/source" to the list, to provide access to, well, the library's source. Basically, it's now requiring a client to know about the library's implementation details.

The garbage collection is a great addition. Is there a way to do it while maintaining the separation between interface and implementation?

### PR DESCRIPTION
**Pull request by m7913d**
Move `format_impl_ptr` to the include directory as it is needed by format.hpp

tests/CMakeLists.txt: If `XLNT_SKIP_INTERNAL_TESTS` is defined, only add the public directory to our include path, to ensure we do not include private files from inside our public header files.

xml_helper.hpp: moved to internal subdirectory to make it clear when we are using internal files.

`format_test_suite`: moved testing of internal API to `format_impl_test_suite`.

Fixes regression introduced by PR #115.

Fixes #118

### CODE REVIEW

**Comment by m7913d** [comment]
Coverage report is available at: [full](https://xlnt-community.github.io/xlnt-coverage/1c22596ef26e19dc11f118004cad38becd6e57c7/differential/index.html) | [review summary](https://xlnt-community.github.io/xlnt-coverage/1c22596ef26e19dc11f118004cad38becd6e57c7/review/index.html)

File: tests/helpers/path_helper.hpp [hunk 1]
```diff
@@ -5,9 +5,36 @@
 
 #include <xlnt/utils/exceptions.hpp>
 #include <xlnt/utils/path.hpp>
-#include <detail/utils/string_helpers.hpp>
 #include <xlnt/internal/features.hpp>
 
+#define XLNT_TEST_U8STRING_LITERAL(a) u8##a
```
[the remark this answers is not in the document]
Comment (doomlaur) [reply tests/helpers/path_helper.hpp]: I agree with you. One the one hand, I personally also dislike that the code is duplicated. On the other hand, this code is unlikely to change for many years to come, and it's not _that_ much code and not very complex either.

An alternative would be to have a more modular approach - a project containing code that could be used by multiple CMake projects, for cases like this. We could think whether this makes sense in the future, but at the moment, I'm not sure how much code could be shared between the CMake projects we currently have. For this piece of code alone (not much code, not complex code, and unlikely to change soon) it probably does not pay off - at least until we have a better reason to create such a project, in case we will have more code to be shared in the future.

[the remark this answers is not in the document]
Comment (m7913d) [reply tests/helpers/path_helper.hpp]: Ok, I will merge the PR. Thanks for your fast review!

Concerning the alternative, I think as long as their is some (non-public) shared code between our unit tests and the main library, this issue could still occur. However, by limiting the amount of shared code (i.e. not sharing the full source folder as it was previously done), we probably decrease the likeliness that this will happen.

**Comment by croueche** [comment]
Yes, thanks for tackling this so quickly, @m7913d . This patch introduces new warnings when building the library (MSVC). There's a forward declaration `class format_impl;` on line 29 in "include/xlnt/internal/format_impl_ptr.hpp" that doesn't match the `struct format_impl` declaration on line 50 in "source/detail/implementations/format_impl.hpp‎".

> ...\xlnt\source\detail\implementations\format_impl.hpp(50,8): warning C4099: 'xlnt::detail::format_impl': type name first seen using 'class' now seen using 'struct' [...\xlnt\build\MSVC\source\xlnt.vcxproj]
>   (compiling source file '../../../source/worksheet/worksheet.cpp')
>       ...\xlnt\source\detail\implementations\format_impl.hpp(50,8):
>       see declaration of 'xlnt::detail::format_impl'
>
